name: Build v2node

on:
  push:
    branches: [ "yulewang-patch-1" ]
  pull_request:
    branches: [ "yulewang-patch-1" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.25'
        cache: true

    - name: Install dependencies
      run: |
        go mod tidy

    - name: Build v2node
      run: |
        VERSION="v0.2.6-custom"
        mkdir -p build_assets
        GOEXPERIMENT=jsonv2 go build -v -o build_assets/v2node -trimpath -ldflags "-X 'github.com/yulewang/v2node/cmd.version=$VERSION' -s -w -buildid="

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: v2node-linux-amd64
        path: build_assets/v2node
